@----------------------------------------------------------
@Labo ARO2 - Micro architecture DECODE
@ HEIG-VD / Institut REDS
@ Prof. M.Starkier
@ Ass. Yanick Saugy, Vincent Theurillat
@----------------------------------------------------------
@	Auteur	:	
@	Date	  :25.04.2013
@----------------------------------------------------------
@
@	Description de votre programme
@
@----------------------------------------------------------

mov r0, #5
mov r1, r0
add r4, r1, #7
add r5, r4, r0
and r4, r5
lsl r2, r5, #3
sub r0, r4, r2
